### PR TITLE
Add new behavior to notification

### PR DESCRIPTION
**Pull request by HeZiGang**
1. Add new behaver notification layer, freeze the layer when mouseover.
2. Fix lint issues.

### CODE REVIEW

**Comment by afc163** [comment]
You can try add test case for this feature.

**Comment by afc163** [comment]
image

**Comment by afc163** [comment]
And add a option for it.

**Comment by HeZiGang** [comment]
@afc163 , I saw that @benjycui said don't need add a new option for it and make the new feature as the default behave. so, i remove the additional option from source code. 

anyway, I can try to add some test case for it.

**Comment by benjycui** [comment]
> And add a option for it, like we discussed in ant-design/ant-design#7513

I think it is OK to be the default behavior of rc-notification.

**Comment by afc163** [comment]
Could be a little wired for message: http://ant.design/components/message/

**Comment by benjycui** [comment]
But if I put cursor on a message/notification, this means that I am reading the message, and it had better not disappear..

**Pull request merged**
