### PR TITLE
feat: Render aria and data props

### PR DESCRIPTION
**Pull request by DylanVann**
*Rebase of: https://github.com/react-component/notification/pull/43*

Passes data-*, aria-*, and role props to Notice to render as html attributes.

### CODE REVIEW

**Comment by afc163** [comment]
conflicted

**Comment by afc163** [comment]
Could u fix conflicting files?

**Comment by DylanVann** [comment]
@afc163 Sorry I didn't see your earlier message. Conflicts are resolved.

**Comment by afc163** [comment]
There are some typescript errors: https://travis-ci.org/github/react-component/notification/jobs/673470049

Could you help to fix it?

**Pull request merged**
