### PR TITLE
Render aria and data props as attributes

### PR DESCRIPTION
**Pull request by matthewlein**
Passes `data-*`, `aria-*`, and `role` props to `Notice` to render as html attributes.

### CODE REVIEW

**Comment by kagd** [comment]
+1

**Comment by kagd** [comment]
Can this be merged? Would be nice for testing purposes :)

**Comment by kagd** [comment]
Can this be merged? Is there anything that needs to be changed?

**Comment by wellwellmissesanderson** [comment]
Can this be merged? Are we waiting on other tasks besides the merge conflicts?

**Pull request closed without merging**
